# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ICer/Project/project_skeleton_sp22/hardware/z1top_proj/z1top_proj.cache/wt [current_project]
set_property parent.project_path /home/ICer/Project/project_skeleton_sp22/hardware/z1top_proj/z1top_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/ICer/Project/project_skeleton_sp22/software/bios151v3/bios151v3.mif
read_verilog -library xil_defaultlib {
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/ALU.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Branch_comp.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/CSR.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Cycle_Counters.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/DMEM_Wen.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Data_align.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/EECS151.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Forwarding.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/IMEM_Wen.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Inst_Counters.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/WB/LDX.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/PCSrc.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/ID/REG_FILES.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/Riscv151.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/Uart_if.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/WEN_align.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/IF/bp_cache.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/IF/branch_predictor.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/clk_wiz.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/ID/control.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/io_circuits/debouncer.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/EXM/exm_wb_regs.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/ID/id_exm_regs.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/ID/immgen.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/IF/pc_reg.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/riscv_core/IF/sat_updn.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/io_circuits/synchronizer.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/io_circuits/uart_receiver.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/io_circuits/uart_transmitter.v
  /home/ICer/Project/project_skeleton_sp22/hardware/src/z1top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ICer/Project/project_skeleton_sp22/hardware/constr/z1top.xdc
set_property used_in_implementation false [get_files /home/ICer/Project/project_skeleton_sp22/hardware/constr/z1top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top z1top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef z1top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file z1top_utilization_synth.rpt -pb z1top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
